apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aivia-test"
  namespace: "aura"
  labels:
    "team": "aura"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isalive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isready"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
  envFrom:
    - secret: aivia-kafka-on-prem
  kafka:
    pool: nav-dev
