apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "aivia-test"
  namespace: "nais"
  labels:
    team: "nais"
spec:
  image: {{image}}
  liveness:
    path: "/internal/isalive"
    initialDelay: 30
  readiness:
    path: "/internal/isready"
    initialDelay: 30
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: LOG_FORMAT
      value: logstash
    - name: LOG_LEVEL
      value: DEBUG
    - name: AIVIA_SOURCE
      value: aiven
  filesFrom:
    - configmap: aivia-topic-mapping
  kafka:
    pool: nav-dev
