name: "Build and deploy aivvia"
on:
  push:
    branches:
    - "main"
env:
  "BASEIMAGE": "ghcr.io/${{ github.repository }}"
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "gradle/wrapper-validation-action@v1"
    - uses: "actions/cache@v2"
      with:
        "path": "~/.gradle/caches"
        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
        "restore-keys": "${{ runner.os }}-gradle-"
    - uses: "actions/setup-java@v1"
      with:
        "java-version": "15"
    - name: "compile and run tests"
      run: "./gradlew build"
    - name: "Set image version"
      run: echo "IMAGE=${BASEIMAGE}:$(date +%Y%m%d%H%M%S)-$(git describe --always --dirty --exclude '*')" >> $GITHUB_ENV
    - name: "Build and publish Docker image"
      run: "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login\
        \ --username $GITHUB_REPOSITORY --password-stdin https://ghcr.io\
        \ && docker push ${IMAGE}"
      env:
        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
